### ISSUE TITLE
have question

### ISSUE THREAD

**Issue by vahidalvandi** [stingbo/gome#12]
Hello
I need an open source maching engine that can process sales orders that are placed in the database through the app, that is, I can finally create something like a binance.
Please advise that this engine of yours can run alongside my app? For example, the membership and wallet sections should be deposited or withdrawn in the my app, and only the trading section should be run in this maching engine?

**Comment by stingbo** [comment]
> Hello I need an open source maching engine that can process sales orders that are placed in the database through the app, that is, I can finally create something like a binance. Please advise that this engine of yours can run alongside my app? For example, the membership and wallet sections should be deposited or withdrawn in the my app, and only the trading section should be run in this maching engine?

Hello
gome is an independent matching engine, which can be independent of your system. It is only responsible for matching, and then outputs the matching results
